# Functions: GitHub Actions work-flow 파일로써, 코드 품질 검사를 자동화하는 설정을 포함하고 있음.

# 본 work-flow의 이름으로써 본 워크플로우 이름을 "check-lint"로 지정함.
name: check-lint

# 본 work-flow는 pull-request가 생성될 때마다 실행됨(본 파일의 목적인 코드 품질 검사를 실행) 
on: [pull_request]

# 이하는 작업의 구성 요소를 의미
jobs:
  check-lint:                                   # 작업 이름
    runs-on: ubuntu-latest                      # 이 작업은 최신 Ubuntu 환경에서 실행될 것임. 

    steps:                                      # 작업에서 수행할 단계를 정의함
      - name: Checkout code                     # 첫번째로 실행되는 step
        uses: actions/checkout@v4               # actions/setup-python@v4을 사용하여 저장소의 코드를 체크아웃함

      - name: Set up Python 3.11                # 두번째로 실행되는 step
        uses: actions/setup-python@v5           # actions/setup-python@v5을 사용하여 python 버전 확인
        with:                                   # 이때 Python 버전은 3.11로 지정
          python-version: "3.11"

      - name: Install dependencies              # 세번째로 실행되는 step: 명령어 실행
        run: |                                  # '|'은 멀티라인 문자열로써, run 키워드 다음에 오는 명령어를 여러줄로 작성 가능하게 해줌
          python3 -m pip install --upgrade pip  

      - name: Check Lint                        # 네번째로 실행되는 step: 명령어 실행
        run: |
          make quality
